# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.ApiKeyAllOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :value_prefix
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :value_prefix => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.ApiKeyAllOf do
  def decode(value, _options) do
    value
  end
end
