# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.CollectionAliasesResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :aliases
  ]

  @type t :: %__MODULE__{
          :aliases => [Typesensory.Model.CollectionAlias.t()]
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.CollectionAliasesResponse do
  import Typesensory.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:aliases, :list, Typesensory.Model.CollectionAlias, options)
  end
end
