# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.CollectionAlias do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :collection_name
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :collection_name => String.t()
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.CollectionAlias do
  def decode(value, _options) do
    value
  end
end
