# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.CollectionSchema do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :fields,
    :default_sorting_field,
    :token_separators,
    :enable_nested_fields,
    :symbols_to_index
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :fields => [Typesensory.Model.Field.t()],
          :default_sorting_field => String.t() | nil,
          :token_separators => [String.t()] | nil,
          :enable_nested_fields => boolean() | nil,
          :symbols_to_index => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.CollectionSchema do
  import Typesensory.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:fields, :list, Typesensory.Model.Field, options)
  end
end
