# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.DeleteDocuments200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :num_deleted
  ]

  @type t :: %__MODULE__{
          :num_deleted => integer()
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.DeleteDocuments200Response do
  def decode(value, _options) do
    value
  end
end
