# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.DeleteDocumentsDeleteDocumentsParametersParameter do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :filter_by,
    :batch_size
  ]

  @type t :: %__MODULE__{
          :filter_by => String.t() | nil,
          :batch_size => integer() | nil
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.DeleteDocumentsDeleteDocumentsParametersParameter do
  def decode(value, _options) do
    value
  end
end
