# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.FacetCountsCountsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :count,
    :highlighted,
    :value
  ]

  @type t :: %__MODULE__{
    :count => integer() | nil,
    :highlighted => String.t | nil,
    :value => String.t | nil
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.FacetCountsCountsInner do
  def decode(value, _options) do
    value
  end
end

