# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.HealthStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ok
  ]

  @type t :: %__MODULE__{
    :ok => boolean()
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.HealthStatus do
  def decode(value, _options) do
    value
  end
end

