# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.ImportDocumentsImportDocumentsParametersParameter do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :batch_size,
    :dirty_values
  ]

  @type t :: %__MODULE__{
          :action => String.t() | nil,
          :batch_size => integer() | nil,
          :dirty_values => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.ImportDocumentsImportDocumentsParametersParameter do
  def decode(value, _options) do
    value
  end
end
