# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.ScopedKeyParameters do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :filter_by,
    :expires_at
  ]

  @type t :: %__MODULE__{
    :filter_by => String.t | nil,
    :expires_at => float() | nil
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.ScopedKeyParameters do
  def decode(value, _options) do
    value
  end
end

