# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchSynonymsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :synonyms
  ]

  @type t :: %__MODULE__{
    :synonyms => [Typesensory.Model.SearchSynonym.t]
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchSynonymsResponse do
  import Typesensory.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:synonyms, :list, Typesensory.Model.SearchSynonym, options)
  end
end

