# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchOverrideSchema do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :rule,
    :includes,
    :excludes,
    :filter_by,
    :remove_matched_tokens
  ]

  @type t :: %__MODULE__{
          :rule => Typesensory.Model.SearchOverrideRule.t(),
          :includes => [Typesensory.Model.SearchOverrideInclude.t()] | nil,
          :excludes => [Typesensory.Model.SearchOverrideExclude.t()] | nil,
          :filter_by => String.t() | nil,
          :remove_matched_tokens => boolean() | nil
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchOverrideSchema do
  import Typesensory.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:rule, :struct, Typesensory.Model.SearchOverrideRule, options)
    |> deserialize(:includes, :list, Typesensory.Model.SearchOverrideInclude, options)
    |> deserialize(:excludes, :list, Typesensory.Model.SearchOverrideExclude, options)
  end
end
