# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchOverrideExclude do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id
  ]

  @type t :: %__MODULE__{
          :id => String.t()
        }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchOverrideExclude do
  def decode(value, _options) do
    value
  end
end
