# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchHighlight do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :field,
    :snippet,
    :snippets,
    :value,
    :values,
    :indices,
    :matched_tokens
  ]

  @type t :: %__MODULE__{
    :field => String.t | nil,
    :snippet => String.t | nil,
    :snippets => [String.t] | nil,
    :value => String.t | nil,
    :values => [String.t] | nil,
    :indices => [integer()] | nil,
    :matched_tokens => [map()] | nil
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchHighlight do
  def decode(value, _options) do
    value
  end
end

