# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchOverridesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :overrides
  ]

  @type t :: %__MODULE__{
    :overrides => [Typesensory.Model.SearchOverride.t]
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchOverridesResponse do
  import Typesensory.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:overrides, :list, Typesensory.Model.SearchOverride, options)
  end
end

