# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SearchOverrideInclude do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :position
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :position => integer()
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.SearchOverrideInclude do
  def decode(value, _options) do
    value
  end
end

