# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Model.SnapshotParameters do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :snapshot_path
  ]

  @type t :: %__MODULE__{
    :snapshot_path => String.t | nil
  }
end

defimpl Poison.Decoder, for: Typesensory.Model.SnapshotParameters do
  def decode(value, _options) do
    value
  end
end

