# NOTE: This file is auto generated by OpenAPI Generator 6.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Typesensory.Api.Debug do
  @moduledoc """
  API calls for all endpoints tagged `Debug`.
  """

  alias Typesensory.Connection
  import Typesensory.RequestBuilder

  @doc """
  Print debugging information
  Print debugging information

  ### Parameters

  - `connection` (Typesensory.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Typesensory.Model.Debug200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec debug(Tesla.Env.client(), keyword()) ::
          {:ok, Typesensory.Model.Debug200Response.t()} | {:error, Tesla.Env.t()}
  def debug(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/debug")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %Typesensory.Model.Debug200Response{}}
    ])
  end
end
